In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('train_LZdllcl.csv')
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met _greaterthan_80percent  awards_won  \
0                  8                                1           0   
1                  4                                0           0   
2                  7                                0           0   
3                 10                                0           0   
4                  2                                0           0   

   avg_training_score  is_promoted  
0                  49            0  
1                  60            0  
2                  50            0  
3                  50            0  
4                  73            0

In [4]:
df.is_promoted.value_counts(normalize=True)*100

0    91.482995
1     8.517005
Name: is_promoted, dtype: float64

In [5]:
df.is_promoted.value_counts()

0    50140
1     4668
Name: is_promoted, dtype: int64

In [6]:
df.columns

Index(['employee_id', 'department', 'region', 'education', 'gender',
       'recruitment_channel', 'no_of_trainings', 'age', 'previous_year_rating',
       'length_of_service', 'KPIs_met _greaterthan_80percent', 'awards_won',
       'avg_training_score', 'is_promoted'],
      dtype='object')

In [7]:
df.shape

(54808, 14)

In [8]:
df.isnull().sum()

employee_id                           0
department                            0
region                                0
education                          2409
gender                                0
recruitment_channel                   0
no_of_trainings                       0
age                                   0
previous_year_rating               4124
length_of_service                     0
KPIs_met _greaterthan_80percent       0
awards_won                            0
avg_training_score                    0
is_promoted                           0
dtype: int64

In [9]:
df.education[df.education.isnull()]=df.education.mode()[0]

C:\Users\Vinay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [10]:
df.previous_year_rating[df.previous_year_rating.isnull()]=3

C:\Users\Vinay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [11]:
edu=pd.get_dummies(df['education'],drop_first=True)

dept=pd.get_dummies(df['department'],drop_first=True)

reg=pd.get_dummies(df['region'],drop_first=True)

gen=pd.get_dummies(df['gender'],drop_first=True)

rec=pd.get_dummies(df['recruitment_channel'],drop_first=True)

df=pd.concat([df,edu],axis=1)

df=pd.concat([df,dept],axis=1)

df=pd.concat([df,reg],axis=1)

df=pd.concat([df,rec],axis=1)

df=pd.concat([df,gen],axis=1)

In [12]:
df.drop(['education','department','employee_id','gender','region','recruitment_channel'],axis=1,inplace=True)

In [13]:
x=df.drop('is_promoted',axis=1)
y=df['is_promoted']

In [14]:
testoriginal=pd.read_csv('test_2umaH9m.csv')

In [15]:
employee=testoriginal.employee_id

In [16]:
testoriginal.previous_year_rating[testoriginal.previous_year_rating.isnull()]=3

C:\Users\Vinay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [17]:
testoriginal.education[testoriginal.education.isnull()]=testoriginal.education.mode()[0]

C:\Users\Vinay\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [18]:
edutest=pd.get_dummies(testoriginal['education'],drop_first=True)

depttest=pd.get_dummies(testoriginal['department'],drop_first=True)

regtest=pd.get_dummies(testoriginal['region'],drop_first=True)

gentest=pd.get_dummies(testoriginal['gender'],drop_first=True)

rectest=pd.get_dummies(testoriginal['recruitment_channel'],drop_first=True)

testoriginal=pd.concat([testoriginal,edutest],axis=1)

testoriginal=pd.concat([testoriginal,depttest],axis=1)

testoriginal=pd.concat([testoriginal,regtest],axis=1)

testoriginal=pd.concat([testoriginal,rectest],axis=1)

testoriginal=pd.concat([testoriginal,gentest],axis=1)

In [19]:
testoriginal.drop(['education','department','employee_id','gender','region','recruitment_channel'],axis=1,inplace=True)

In [20]:
x_test1=testoriginal
#y_test=testoriginal['is_promoted']


In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [23]:
from sklearn import tree
from sklearn.metrics import confusion_matrix

In [24]:
clf=tree.DecisionTreeClassifier()
clf.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
confidance=clf.score(x_test,y_test)

In [26]:
confidance

0.896551724137931

In [27]:
y_pred=clf.predict(x_test)

In [28]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
c=confusion_matrix(y_test,y_pred)
c

array([[9412,  620],
       [ 514,  416]], dtype=int64)

In [30]:
#Overall Accuracy
(c[0,0]+c[1,1])/np.sum(c)*100

89.65517241379311

In [31]:
#recall
9361/(9361+601)

0.9396707488456133

In [32]:
#Specificity
451/(451+549)

0.451

In [33]:
Precision=c[0,0]/(c[0,0]+[1,0])
Precision

array([0.99989376, 1.        ])

In [34]:
Recall=c[0,0]/(c[0,0]+c[0,1])
Recall

0.9381977671451356

In [35]:
Fscore=2*(Recall*Precision)/(Recall+Precision)
Fscore

array([0.96806377, 0.96811356])

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94     10032
           1       0.40      0.45      0.42       930

   micro avg       0.90      0.90      0.90     10962
   macro avg       0.67      0.69      0.68     10962
weighted avg       0.90      0.90      0.90     10962



#### building model of GBM

In [37]:
#import libraries
from sklearn.ensemble import GradientBoostingClassifier #For Classification
from sklearn.ensemble import GradientBoostingRegressor #For Regression



In [38]:
#use GBM function
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=3)
clf.fit(x_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=1.0, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=1.0, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

#### Now predicting values for test data

In [39]:
predictions=clf.predict(x_test)


In [40]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.95      0.94      0.94     10032
           1       0.40      0.45      0.42       930

   micro avg       0.90      0.90      0.90     10962
   macro avg       0.67      0.69      0.68     10962
weighted avg       0.90      0.90      0.90     10962



In [41]:
predictions=pd.DataFrame(predictions,columns=['is_promoted'])
employee=pd.DataFrame(employee,columns=['employee_id'])

In [42]:
predictions=pd.concat([employee,predictions],axis=1)

In [43]:
predictions.to_csv('xplorer.csv',index=False)#,columns=['employee_id','is_promoted'])

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [45]:
logreg = LogisticRegression()
logreg.fit(x_train, y_train)

C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [46]:
y_pred = logreg.predict(x_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(x_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.93


In [47]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96     10032
           1       0.87      0.22      0.35       930

   micro avg       0.93      0.93      0.93     10962
   macro avg       0.90      0.61      0.66     10962
weighted avg       0.93      0.93      0.91     10962



In [48]:
import statsmodels.api as sm
logit_model=sm.Logit(y_train,x_train)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.247305
         Iterations 8
                                 Results: Logit
Model:                   Logit                 Pseudo R-squared:      0.151     
Dependent Variable:      is_promoted           AIC:                   21792.6760
Date:                    2018-11-24 00:29      BIC:                   22253.1633
No. Observations:        43846                 Log-Likelihood:        -10843.   
Df Model:                52                    LL-Null:               -12777.   
Df Residuals:            43793                 LLR p-value:           0.0000    
Converged:               1.0000                Scale:                 1.0000    
No. Iterations:          8.0000                                                 
--------------------------------------------------------------------------------
                                 Coef.  Std.Err.    z     P>|z|   [0.025  0.975]
----------------------------------------

In [49]:
#X = .loc[:, data_final.columns != 'is_promoted']
#y = data_final.loc[:, data_final.columns == 'is_promoted']
from imblearn.over_sampling import SMOTE
os = SMOTE(random_state=0)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)
columns = x_train.columns
os_data_X,os_data_y=os.fit_sample(x_train, y_train)
os_data_X = pd.DataFrame(data=os_data_X,columns=columns )
os_data_y= pd.DataFrame(data=os_data_y,columns=['y'])
# we can Check the numbers of our data
print("length of oversampled data is ",len(os_data_X))
print("Number of no subscription in oversampled data",len(os_data_y[os_data_y['y']==0]))
print("Number of subscription",len(os_data_y[os_data_y['y']==1]))
print("Proportion of no subscription data in oversampled data is ",len(os_data_y[os_data_y['y']==0])/len(os_data_X))
print("Proportion of subscription data in oversampled data is ",len(os_data_y[os_data_y['y']==1])/len(os_data_X))


length of oversampled data is  70166
Number of no subscription in oversampled data 35083
Number of subscription 35083
Proportion of no subscription data in oversampled data is  0.5
Proportion of subscription data in oversampled data is  0.5


In [50]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


logreg = LogisticRegression()
rfe = RFE(logreg, 20)
rfe = rfe.fit(os_data_X, os_data_y.values.ravel())
print(rfe.support_)
print(rfe.ranking_)

C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence t

[False False False False  True  True False False False False  True  True
 False False False False False False  True False False False False  True
 False  True  True False  True  True False False  True False  True False
 False  True False False  True  True  True  True False  True  True False
 False  True False False False]
[15 32  3 33  1  1 20 23 28 16  1  1 17 19  2 18 12 10  1  6  9  4  8  1
 24  1  1 11  1  1 22 25  1 21  1  7 31  1 34 13  1  1  1  1 14  1  1 26
  5  1 29 30 27]


In [51]:
mask = rfe.get_support() #list of booleans
new_features = [] # The list of your K best features

for bool, feature in zip(mask, x):
    if bool:
        new_features.append(feature)

In [52]:
new_features

['KPIs_met _greaterthan_80percent',
 'awards_won',
 'HR',
 'Legal',
 'region_11',
 'region_16',
 'region_18',
 'region_19',
 'region_20',
 'region_21',
 'region_24',
 'region_26',
 'region_29',
 'region_31',
 'region_32',
 'region_33',
 'region_34',
 'region_5',
 'region_6',
 'region_9']

In [53]:
X=os_data_X[new_features]
y=os_data_y['y']

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

C:\Users\Vinay\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [55]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.72


In [56]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[7309 3181]
 [2771 7789]]


In [57]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.70      0.71     10490
           1       0.71      0.74      0.72     10560

   micro avg       0.72      0.72      0.72     21050
   macro avg       0.72      0.72      0.72     21050
weighted avg       0.72      0.72      0.72     21050

